name = "Escher"
uuid = "8cc96de1-1b23-48cb-9272-618d67962629"
authors = ["stelmo <stelmozors@gmail.com>"]
version = "0.7.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"

[compat]
JSON = "0.21"
Makie = "0.16, 0.17"
julia = "1.6, 1.7, 1.8, 1.9"
DocStringExtensions = "0.8, 0.9"
